(function(){
  function H(){return window.__horizonte?.db}
  function E(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  const subjects=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  const hardTemplates={
    'Português':['Analise um texto argumentativo e identifique tese, estratégias de persuasão e possíveis pressupostos.','Compare dois trechos e explique como escolhas lexicais e sintáticas alteram o sentido produzido.','Em um texto de opinião, avalie a relação entre coesão, coerência e progressão argumentativa.','Identifique uma possível ambiguidade e proponha uma reescrita que elimine a dupla interpretação.','Analise os efeitos de sentido produzidos por ironia, intertextualidade ou modalização em um contexto real.'],
    'Matemática':['Resolva e justifique um problema envolvendo função, restrições do domínio e interpretação do resultado no contexto.','Analise geometricamente uma situação e determine as condições necessárias para que uma relação entre grandezas seja satisfeita.','Modele uma situação por meio de uma equação ou sistema e discuta quais soluções são admissíveis.','Determine um parâmetro desconhecido a partir de condições algébricas e verifique a consistência da resposta.','Compare dois métodos de resolução para um problema e justifique qual apresenta maior eficiência ou menor margem de erro.'],
    'História':['Analise duas fontes históricas de naturezas distintas e avalie seus contextos, interesses e limites como evidências.','Explique relações de causa, consequência e continuidade em um processo histórico sem reduzir o fenômeno a uma única causa.','Compare diferentes interpretações de um acontecimento histórico e sustente uma conclusão com argumentos.','Relacione transformações políticas, econômicas e sociais de determinado período e explique como elas se influenciaram.','Avalie criticamente uma afirmação histórica, distinguindo fato, interpretação e anacronismo.'],
    'Geografia':['Interprete dados espaciais e explique como fatores econômicos, ambientais e demográficos produzem determinada configuração territorial.','Analise uma situação de urbanização considerando segregação socioespacial, infraestrutura e dinâmica populacional.','Relacione clima, relevo, hidrografia e ação humana para explicar uma transformação ambiental.','Compare dois territórios e justifique diferenças de desenvolvimento usando indicadores e localização.','Avalie impactos de uma atividade econômica sobre território, população e ambiente, propondo uma medida de mitigação.'],
    'Biologia':['Analise uma situação-problema envolvendo genética e justifique a probabilidade de determinados fenótipos.','Explique como alterações em uma etapa de um processo biológico podem afetar as etapas seguintes.','Interprete dados experimentais e formule uma conclusão compatível com as evidências apresentadas.','Relacione estrutura e função em diferentes níveis de organização dos seres vivos.','Analise uma cadeia ou teia alimentar e preveja consequências de uma alteração populacional.'],
    'Física':['Modele uma situação física, identifique as grandezas relevantes, estabeleça as equações e interprete o resultado.','Analise um movimento a partir de dados e determine grandezas desconhecidas justificando cada etapa.','Resolva uma situação envolvendo conservação de energia e discuta perdas e hipóteses do modelo.','Determine a força resultante em um sistema e explique como mudanças nas condições alteram o movimento.','Compare dois modelos físicos para o mesmo fenômeno e indique quais hipóteses tornam cada modelo válido.'],
    'Química':['Analise uma reação química a partir de dados e determine relações quantitativas entre reagentes e produtos.','Explique como alterações de concentração, temperatura ou pressão podem deslocar um equilíbrio químico.','Interprete uma situação de transformação da matéria distinguindo evidências de reação química e mudança física.','Determine propriedades de uma substância a partir de informações sobre estrutura, ligações e interações.','Analise um procedimento experimental, identifique uma possível fonte de erro e proponha uma melhoria.'],
    'Inglês':['Read a challenging passage and infer the author’s purpose, tone, implicit meaning and supporting evidence.','Analyze how tense, modality and word choice change the meaning of a sentence in context.','Compare two versions of a passage and explain the effect of grammatical and lexical choices.','Infer the meaning of an unfamiliar expression from context and justify the inference using textual evidence.','Evaluate an argument in English, identifying assumptions, evidence and a possible counterargument.']
  };
  function makeQuestions(sub,key,topic){let b=hardTemplates[sub]||hardTemplates['Português'],out=[];for(let i=0;i<25;i++){let j=(i+key)%b.length;let q=b[j]+' Assunto: '+topic+'. Questão '+(i+1)+'. Desenvolva a resposta com justificativa e, quando aplicável, cálculos ou evidências.';out.push({n:i+1,q,opts:['A resposta exige análise e justificativa fundamentada.','A resposta deve considerar apenas uma variável, ignorando o contexto.','A resposta correta depende de uma hipótese não indicada no enunciado.','Nenhuma das anteriores'],correct:null})}return out}
  function unitAvg(s,p){let a=subjects.map(x=>{let g=s.grades?.[p]?.[x]||{},v=['n1','n2','n3'].map(k=>g[k]).filter(v=>v!==''&&v!=null).map(Number);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null}).filter(x=>x!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function recoverySubs(s,p){return subjects.filter(x=>(unitAvgSubject(s,p,x)??10)<6)}
  function unitAvgSubject(s,p,sub){let g=s.grades?.[p]?.[sub]||{},a=['n1','n2','n3'].map(k=>g[k]).filter(v=>v!==''&&v!=null).map(Number);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function addNav(){let aside=document.querySelector('aside');if(!aside||aside.querySelector('[data-page="recuperacao"]'))return;const html='<button class="nav" data-page="recuperacao">🎯 Recuperação</button><button class="nav" data-page="provas">📚 Provas</button>';let b=[...aside.querySelectorAll('.nav')].find(x=>x.dataset.page==='boletins');b?.insertAdjacentHTML('afterend',html)}
  function addSections(){let main=document.querySelector('main');if(!main||document.getElementById('recuperacao'))return;main.insertAdjacentHTML('beforeend',`<section id="recuperacao" class="page"><div class="head"><div><h2>Recuperação</h2><p>Gerencie a recuperação por aluno e matéria. Não há geração automática de simulado.</p></div></div><div class="filters"><select id="rxUnit"></select><select id="rxClass"></select><select id="rxPeriod"><option value="1">1º Bimestre</option><option value="2">2º Bimestre</option></select></div><div class="panel"><div class="ph"><b>Alunos em recuperação</b><span id="rxCount" class="muted"></span></div><div class="wrap"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Disciplinas</th></tr></thead><tbody id="rxTable"></tbody></table></div></div></section><section id="provas" class="page"><div class="head"><div><h2>Provas</h2><p>Gere uma única prova difícil para toda a turma, com 25 questões.</p></div></div><div class="filters"><select id="pxUnit"></select><select id="pxClass"></select><select id="pxSubject"></select><input id="pxTopic" placeholder="Assunto da prova" style="min-width:220px"><button class="gold" id="pxGenerate">Gerar prova da turma</button></div><div id="pxBox" class="panel"></div></section>`)}
  function fill(id,arr){let e=document.getElementById(id);if(e)e.innerHTML=arr.map(x=>`<option value="${E(x.value??x)}">${E(x.label??x)}</option>`).join('')}
  function setupFilters(){let d=H();if(!d)return;fill('rxUnit',d.units);fill('pxUnit',d.units);fill('pxSubject',subjects);let ru=document.getElementById('rxUnit'),pu=document.getElementById('pxUnit');if(ru)fillClasses('rxClass',ru.value);if(pu)fillClasses('pxClass',pu.value);ru?.addEventListener('change',()=>{fillClasses('rxClass',ru.value);renderRecovery()});pu?.addEventListener('change',()=>fillClasses('pxClass',pu.value));document.getElementById('rxClass')?.addEventListener('change',renderRecovery);document.getElementById('rxPeriod')?.addEventListener('change',renderRecovery);document.getElementById('pxGenerate')?.addEventListener('click',generateExam)}
  function fillClasses(id,u){let d=H(),e=document.getElementById(id);if(e)e.innerHTML=d.classes.filter(c=>c.unit===u).map(c=>`<option value="${c.id}">${E(c.name)}</option>`).join('')}
  function renderRecovery(){let d=H(),p=+document.getElementById('rxPeriod')?.value||1,c=document.getElementById('rxClass')?.value,s=(d?.students||[]).filter(x=>x.class===c&&recoverySubs(x,p).length);let count=document.getElementById('rxCount');if(count)count.textContent=s.length+' aluno(s)';let t=document.getElementById('rxTable');if(!t)return;t.innerHTML=s.map(x=>{let subs=recoverySubs(x,p);return `<tr><td><b>${E(x.name)}</b><br><small>${x.id}</small></td><td>${E(d.classes.find(c=>c.id===x.class)?.name||x.class)}</td><td>${subs.map(z=>`<span class="badge rec" style="margin-right:4px">${E(z)} · ${unitAvgSubject(x,p,z).toFixed(1)}</span>`).join('')}</td></tr>`}).join('')||'<tr><td colspan="3">Nenhum aluno em recuperação nesta turma/bimestre.</td></tr>'}
  function generateExam(){let d=H(),c=document.getElementById('pxClass')?.value,sub=document.getElementById('pxSubject')?.value,topic=document.getElementById('pxTopic')?.value.trim();if(!c||!sub)return alert('Selecione a turma e a matéria.');if(!topic)return alert('Informe o assunto da prova.');let cls=d.classes.find(x=>x.id===c),ex={id:'EX-'+Date.now(),type:'regular',class:c,subject:sub,topic,questions:makeQuestions(sub,c.length*7+sub.length*11,topic),createdAt:new Date().toISOString()};d.exams??=[];d.exams.push(ex);showExam(ex);window.save?.().then(()=>window.toast?.('Prova difícil da turma gerada e salva.'))}
  function showExam(ex){let box=document.getElementById('pxBox');if(!box)return;let cls=H().classes.find(c=>c.id===ex.class);box.innerHTML=`<div class="ph"><b>${E(ex.subject)} — ${E(cls?.name||ex.class)}</b><span>Assunto: ${E(ex.topic||'Não informado')} · 25 questões · uma prova para toda a turma</span></div><div class="pad">${ex.questions.map(q=>`<div class="question"><b>${q.n}. ${E(q.q)}</b>${q.opts.map((o,i)=>`<div>${String.fromCharCode(65+i)}) ${E(o)}</div>`).join('')}</div>`).join('')}<button class="gold" onclick="window.print()">Imprimir prova</button></div>`}
  function showList(){let d=H(),es=(d.exams||[]).filter(e=>e.type!=='recovery'),box=document.getElementById('pxBox');if(!box)return;box.innerHTML=`<div class="pad"><b>${es.length} prova(s) de turma armazenada(s).</b><div class="grid2" style="margin-top:12px">${es.slice(-60).map(e=>`<div class="tile"><b>${E(e.subject)}</b><br>${E(d.classes.find(c=>c.id===e.class)?.name||e.class)}<br><span class="muted">${E(e.topic||'Sem assunto')} · 25 questões</span><br><button class="btn" onclick="window.hzShowExam('${E(e.id)}')">Abrir</button></div>`).join('')}</div></div>`}
  window.hzShowExam=function(id){let e=H().exams.find(x=>x.id===id);if(e&&e.type!=='recovery')showExam(e)};
  function patch(){addNav();addSections();setupFilters();renderRecovery();showList();window.save?.(true)}
  function hook(){patch();let old=window.showApp;if(old&&!old.__hz){let f=window.showApp;window.showApp=async function(){let r=f.apply(this,arguments);setTimeout(patch,0);return r};window.showApp.__hz=true}}
  window.addEventListener('DOMContentLoaded',()=>setTimeout(hook,50));window.addEventListener('load',()=>setTimeout(hook,100));setTimeout(hook,500);
})();