(function(){
  function H(){return window.__horizonte?.db}
  function E(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  const subjects=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  const templates={
    'Português':['Qual é a função principal de um substantivo?','Qual classe de palavra indica ação ou estado?','Qual é o antônimo de “rápido”?','Qual é um sinônimo de “feliz”?','Em uma frase, o sujeito indica o quê?'],
    'Matemática':['Quanto é 25% de 80?','Qual é o resultado de 7×8?','Qual é a raiz quadrada de 81?','Se x+5=12, qual é x?','Qual é a área de um quadrado de lado 4?'],
    'História':['O que é uma fonte histórica?','O que significa colonização?','Qual é a função de uma linha do tempo?','O que caracteriza a Idade Moderna?','Por que estudar fontes históricas?'],
    'Geografia':['O que é latitude?','O que é clima?','Qual é a função de um mapa?','O que é urbanização?','O que caracteriza uma bacia hidrográfica?'],
    'Biologia':['Qual é a unidade básica dos seres vivos?','Qual organela está ligada à produção de energia?','O que é fotossíntese?','Qual sistema transporta o sangue?','O que é uma cadeia alimentar?'],
    'Física':['Qual é a unidade de força no SI?','O que é velocidade média?','O que é aceleração?','Qual é a unidade de energia no SI?','O que é força resultante?'],
    'Química':['Qual é a unidade básica da matéria?','O que representa a fórmula H2O?','O que é uma mistura?','Qual é a diferença entre átomo e molécula?','O que é uma reação química?'],
    'Inglês':['Qual é a tradução de “book”?','Qual é o plural de “child”?','Qual verbo completa “I ___ a student”?','O que significa “good morning”?','Qual é o passado de “go”?']
  };
  const answers={'Português':['Nomeia seres, coisas ou ideias','Ação ou estado','Lento','Contente','Quem realiza ou sofre a ação'],'Matemática':['20','56','9','7','16'],'História':['Documento, objeto ou relato do passado','Domínio e ocupação de territórios','Organizar acontecimentos em sequência','Renascimento e expansão marítima','Conhecer e interpretar o passado'],'Geografia':['Distância angular ao norte ou sul do Equador','Conjunto das condições atmosféricas médias','Representar e localizar elementos no espaço','Crescimento da população urbana','Área drenada por um rio principal'],'Biologia':['Célula','Mitocôndria','Produção de matéria orgânica usando luz','Circulatório','Transferência de energia entre organismos'],'Física':['Newton','Distância percorrida dividida pelo tempo','Variação da velocidade no tempo','Joule','Soma das forças que atuam no corpo'],'Química':['Átomo','Água','Combinação física de substâncias','Molécula é formada por átomos ligados','Transformação que forma novas substâncias'],'Inglês':['Livro','Children','Am','Bom dia','Went']};
  function makeQuestions(sub,key){let b=templates[sub],a=answers[sub],out=[];for(let i=0;i<25;i++){let j=(i+key)%5,correct=a[j],opts=[correct,'Nenhuma das anteriores','A alternativa não se aplica','Todas as anteriores'],shift=(i*3+key)%4;opts=opts.slice(shift).concat(opts.slice(0,shift));out.push({n:i+1,q:b[j]+' — questão '+(i+1),opts,correct})}return out}
  function unitAvg(s,p){let d=H(),a=subjects.map(x=>{let g=s.grades?.[p]?.[x]||{},v=['n1','n2','n3'].map(k=>g[k]).filter(v=>v!==''&&v!=null).map(Number);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null}).filter(x=>x!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function recoverySubs(s,p){return subjects.filter(x=>(unitAvgSubject(s,p,x)??10)<7)}
  function unitAvgSubject(s,p,sub){let g=s.grades?.[p]?.[sub]||{},a=['n1','n2','n3'].map(k=>g[k]).filter(v=>v!==''&&v!=null).map(Number);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function seedAcademic(){let d=H();if(!d||d.students.length!==150)return;if(d.stateVersion!==2){d.students.forEach(s=>{s.grades={};s.recovery={};});}d.stateVersion=2;d.students.forEach((s,i)=>{s.grades??={};s.attendance??={};s.recovery??={};for(const p of [1,2]){if(Object.keys(s.grades[p]||{}).length)continue;s.grades[p]={};for(let j=0;j<subjects.length;j++){let base=i>=135?(5.4+((i+j*3)%10)/10+(p===2?.15:0)):Math.min(9.5,7.2+((i*3+j*2)%18)/10);s.grades[p][subjects[j]]={n1:+Math.max(0,base-.6).toFixed(1),n2:+Math.min(10,base+.1).toFixed(1),n3:+Math.min(10,base+.5).toFixed(1)}}}})}
  function addNav(){let aside=document.querySelector('aside');if(!aside||aside.querySelector('[data-page="recuperacao"]'))return;const html='<button class="nav" data-page="recuperacao">🎯 Recuperação</button><button class="nav" data-page="provas">📚 Provas</button>';let b=[...aside.querySelectorAll('.nav')].find(x=>x.dataset.page==='boletins');b?.insertAdjacentHTML('afterend',html)}
  function addSections(){let main=document.querySelector('main');if(!main||document.getElementById('recuperacao'))return;main.insertAdjacentHTML('beforeend',`<section id="recuperacao" class="page"><div class="head"><div><h2>Recuperação</h2><p>Alunos com média abaixo de 7 nos 1º e 2º bimestres. O simulado vale até 7,0 pontos.</p></div></div><div class="filters"><select id="rxUnit"></select><select id="rxClass"></select><select id="rxPeriod"><option value="1">1º Bimestre</option><option value="2">2º Bimestre</option></select></div><div class="panel"><div class="ph"><b>Alunos em recuperação</b><span id="rxCount" class="muted"></span></div><div class="wrap"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Disciplinas</th><th>Ação</th></tr></thead><tbody id="rxTable"></tbody></table></div></div></section><section id="provas" class="page"><div class="head"><div><h2>Provas</h2><p>25 questões por prova, total de 10,0 pontos.</p></div></div><div class="filters"><select id="pxUnit"></select><select id="pxClass"></select><select id="pxSubject"></select><button class="gold" id="pxGenerate">Gerar prova</button><button class="btn" id="pxAll">Gerar todas as 48 provas</button></div><div id="pxBox" class="panel"></div></section>`)}
  function fill(id,arr){let e=document.getElementById(id);if(e)e.innerHTML=arr.map(x=>`<option value="${E(x.value??x)}">${E(x.label??x)}</option>`).join('')}
  function setupFilters(){let d=H();if(!d)return;fill('rxUnit',d.units);fill('pxUnit',d.units);fill('pxSubject',subjects);let ru=document.getElementById('rxUnit'),pu=document.getElementById('pxUnit');if(ru)fillClasses('rxClass',ru.value);if(pu)fillClasses('pxClass',pu.value);ru?.addEventListener('change',()=>{fillClasses('rxClass',ru.value);renderRecovery()});pu?.addEventListener('change',()=>fillClasses('pxClass',pu.value));document.getElementById('rxClass')?.addEventListener('change',renderRecovery);document.getElementById('rxPeriod')?.addEventListener('change',renderRecovery);document.getElementById('pxGenerate')?.addEventListener('click',generateExam);document.getElementById('pxAll')?.addEventListener('click',generateAll)}
  function fillClasses(id,u){let d=H(),e=document.getElementById(id);if(e)e.innerHTML=d.classes.filter(c=>c.unit===u).map(c=>`<option value="${c.id}">${E(c.name)}</option>`).join('')}
  function renderRecovery(){let d=H(),p=+document.getElementById('rxPeriod')?.value||1,c=document.getElementById('rxClass')?.value,s=(d?.students||[]).filter(x=>x.class===c&&recoverySubs(x,p).length);let count=document.getElementById('rxCount');if(count)count.textContent=s.length+' aluno(s)';let t=document.getElementById('rxTable');if(!t)return;t.innerHTML=s.map(x=>{let subs=recoverySubs(x,p);return `<tr><td><b>${E(x.name)}</b><br><small>${x.id}</small></td><td>${E(d.classes.find(c=>c.id===x.class)?.name||x.class)}</td><td>${subs.map(z=>`<span class="badge rec" style="margin-right:4px">${E(z)} · ${unitAvgSubject(x,p,z).toFixed(1)}</span>`).join('')}</td><td>${subs.map(z=>`<button class="btn" onclick="window.hzRecovery('${x.id}',${p},'${E(z)}')">Prova</button>`).join(' ')}</td></tr>`}).join('')||'<tr><td colspan="4">Nenhum aluno em recuperação nesta turma/bimestre.</td></tr>'}
  window.hzRecovery=function(id,p,sub){let d=H(),s=d.students.find(x=>x.id===id),key=(+id%97)+p*13+sub.length*7,ex={id:'REC-'+id+'-'+p+'-'+sub,type:'recovery',student:id,studentName:s.name,class:s.class,period:p,subject:sub,questions:makeQuestions(sub,key),createdAt:new Date().toISOString()};d.exams??=[];d.exams=d.exams.filter(x=>x.id!==ex.id);d.exams.push(ex);showExam(ex);document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelector('[data-page="provas"]')?.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('provas')?.classList.add('active');window.save?.().then(()=>window.toast?.('Prova exclusiva gerada.'))}
  function generateExam(){let d=H(),c=document.getElementById('pxClass').value,sub=document.getElementById('pxSubject').value,ex={id:'EX-'+Date.now(),type:'regular',class:c,subject:sub,questions:makeQuestions(sub,c.length*7+sub.length*11),createdAt:new Date().toISOString()};d.exams??=[];d.exams.push(ex);showExam(ex);window.save?.().then(()=>window.toast?.('Prova gerada e salva.'))}
  function generateAll(){let d=H();d.exams??=[];for(const c of d.classes)for(const sub of subjects){let id='EX-'+c.id+'-'+sub.replace(/\W/g,'').slice(0,8);d.exams=d.exams.filter(x=>x.id!==id);d.exams.push({id,type:'regular',class:c.id,subject:sub,questions:makeQuestions(sub,c.id.charCodeAt(0)+sub.length),createdAt:new Date().toISOString()})}showList();window.save?.().then(()=>window.toast?.('48 provas geradas.'))}
  function showExam(ex){let box=document.getElementById('pxBox');if(!box)return;box.innerHTML=`<div class="ph"><b>${E(ex.subject)} — ${E(H().classes.find(c=>c.id===ex.class)?.name||ex.class)}</b><span>25 questões · 10,0 pontos</span></div><div class="pad">${ex.type==='recovery'?'<p><b>Prova exclusiva de recuperação</b> · '+E(ex.studentName)+'</p>':''}${ex.questions.map(q=>`<div class="question"><b>${q.n}. ${E(q.q)}</b>${q.opts.map((o,i)=>`<div>${String.fromCharCode(65+i)}) ${E(o)}</div>`).join('')}</div>`).join('')}<button class="gold" onclick="window.print()">Imprimir prova</button></div>`}
  function showList(){let d=H(),es=d.exams||[],box=document.getElementById('pxBox');if(!box)return;box.innerHTML=`<div class="pad"><b>${es.length} prova(s) armazenada(s).</b><div class="grid2" style="margin-top:12px">${es.slice(-60).map(e=>`<div class="tile"><b>${E(e.subject)}</b><br>${E(d.classes.find(c=>c.id===e.class)?.name||e.class)}${e.type==='recovery'?'<br><span class="muted">Recuperação · '+E(e.studentName)+'</span>':''}<br><span class="muted">25 questões · 10,0 pontos</span><br><button class="btn" onclick="window.hzShowExam('${E(e.id)}')">Abrir</button></div>`).join('')}</div></div>`}
  window.hzShowExam=function(id){let e=H().exams.find(x=>x.id===id);if(e)showExam(e)};
  function patch(){addNav();addSections();seedAcademic();setupFilters();renderRecovery();showList();}
  function hook(){patch();let old=window.showApp;if(old&&!old.__hz){let f=window.showApp;window.showApp=async function(){let r=f.apply(this,arguments);setTimeout(patch,0);return r};window.showApp.__hz=true}}
  window.addEventListener('DOMContentLoaded',()=>setTimeout(hook,50));window.addEventListener('load',()=>setTimeout(hook,100));setTimeout(hook,500);
})();