(function(){
  const SUBJECTS=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  function db(){return window.__horizonte?.db||window.db}
  function notes(g){return ['n1','n2','n3','n4'].map(k=>g?.[k]).filter(v=>v!==''&&v!=null).map(Number)}
  function average(g){const a=notes(g);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function unitAverage(s,p){const d=db();const a=SUBJECTS.map(sub=>average(s.grades?.[p]?.[sub]||{})).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function situation(m){return m==null?['Sem nota','neutral']:m>=6?['Aprovado','ok']:m>=5?['Recuperação','rec']:['Reprovado','bad']}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function resetSecondBimester(){const d=db();if(!d||!Array.isArray(d.students))return false;let changed=false;d.students.forEach(s=>{s.grades??={};if(s.grades[2]&&Object.keys(s.grades[2]).length){delete s.grades[2];changed=true;}});d.stateVersion=2;return changed}
  function patchPeriodUI(){const e=document.getElementById('gradePeriod');if(e){e.innerHTML='<option value="1">1º Bimestre — Fechado</option><option value="2">2º Bimestre — Aberto</option><option value="3">3º Bimestre — Aberto</option>';}const h=document.querySelector('#notas .head p');if(h)h.textContent='1º bimestre fechado. 2º bimestre aberto para lançamento. 3º bimestre aberto.';const th=document.querySelector('#gradeTable')?.closest('table')?.querySelector('thead tr');if(th){const cells=th.querySelectorAll('th');if(cells.length>=5){cells[3].textContent='Nota 3';const n4=Array.from(cells).find(x=>x.textContent.trim()==='Nota 4');if(!n4){const avgTh=Array.from(cells).find(x=>x.textContent.trim()==='Média');if(avgTh){const x=document.createElement('th');x.textContent='Nota 4';avgTh.parentNode.insertBefore(x,avgTh);}}}}}
  function renderGrades4(){const d=db(),cl=document.getElementById('gradeClass')?.value,sub=document.getElementById('gradeSubject')?.value,p=+(document.getElementById('gradePeriod')?.value||1),t=document.getElementById('gradeTable');if(!d||!t)return;const list=(d.students||[]).filter(x=>x.class===cl);t.innerHTML=list.length?list.map(s=>{const g=s.grades?.[p]?.[sub]||{},m=average(g),z=situation(m);return '<tr><td><strong>'+esc(s.name)+'</strong><br><small class="small">'+esc(s.id)+'</small></td>'+['n1','n2','n3','n4'].map(k=>'<td><input class="gradeInput" data-id="'+esc(s.id)+'" data-k="'+k+'" type="number" min="0" max="10" step="0.1" value="'+(g[k]??'')+'"></td>').join('')+'<td>'+(m==null?'—':m.toFixed(1))+'</td><td><span class="badge '+z[1]+'">'+z[0]+'</span></td></tr>'}).join(''):'<tr><td colspan="8">Nenhum aluno nesta turma.</td></tr>';}
  window.saveGrades=function(){const d=db(),p=+(document.getElementById('gradePeriod')?.value||1),sub=document.getElementById('gradeSubject')?.value;if(!d||!sub)return;if(p===1){alert('O 1º bimestre está fechado.');return;}document.querySelectorAll('.gradeInput').forEach(i=>{const s=d.students.find(x=>x.id===i.dataset.id);if(!s)return;s.grades??={};s.grades[p]??={};s.grades[p][sub]??={};s.grades[p][sub][i.dataset.k]=i.value===''?'':Number(i.value)});Promise.resolve(window.save?.()).then(()=>{renderGrades4();window.renderAll?.();window.toast?.('Notas salvas com sucesso!')});}
  function apply(){patchPeriodUI();const changed=resetSecondBimester();renderGrades4();if(changed)Promise.resolve(window.save?.(true));}
  window.addEventListener('load',()=>setTimeout(apply,350));
  window.addEventListener('DOMContentLoaded',()=>setTimeout(apply,250));
  setTimeout(apply,900);
})();
