(function(){
  const SUBJECTS=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  function db(){return window.__horizonte?.db||window.db}
  function notes(g){return ['n1','n2','n3','n4'].map(k=>g?.[k]).filter(v=>v!==''&&v!=null&&!Number.isNaN(Number(v))).map(Number)}
  function average(g){const a=notes(g);return a.length?a.reduce((x,y)=>x+y,0)/3:null}
  function unitAverage(s,p){const a=SUBJECTS.map(sub=>average(s.grades?.[p]?.[sub]||{})).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function situation(m){return m==null?['Sem nota','neutral']:m>=6?['Aprovado','ok']:m>=5?['Recuperação','rec']:['Reprovado','bad']}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function patchPeriodUI(){const e=document.getElementById('gradePeriod'),sub=document.getElementById('gradeSubject')?.value||'';if(e){const v=e.value;e.innerHTML='<option value="1">1º Bimestre — Fechado</option><option value="2">2º Bimestre — '+(sub==='Português'?'Aberto':'Fechado')+'</option><option value="3">3º Bimestre — Aberto</option>';e.value=v||'2';}const h=document.querySelector('#notas .head p');if(h)h.textContent='1º bimestre fechado. 2º bimestre fechado para todas as matérias, exceto Português. 3º bimestre aberto.'}
  function renderGrades4(){const d=db(),cl=document.getElementById('gradeClass')?.value,sub=document.getElementById('gradeSubject')?.value,p=+(document.getElementById('gradePeriod')?.value||1),t=document.getElementById('gradeTable');if(!d||!t)return;const locked=p===1||(p===2&&sub!=='Português');const list=(d.students||[]).filter(x=>x.class===cl);t.innerHTML=list.length?list.map(s=>{const g=s.grades?.[p]?.[sub]||{},m=average(g),z=situation(m);return '<tr><td><strong>'+esc(s.name)+'</strong><br><small>'+esc(s.id)+'</small></td>'+['n1','n2','n3','n4'].map(k=>'<td><input class="gradeInput" data-id="'+esc(s.id)+'" data-k="'+k+'" type="number" min="0" max="10" step="0.1" value="'+(g[k]??'')+'" '+(locked?'disabled':'')+'></td>').join('')+'<td>'+(m==null?'—':m.toFixed(2))+'</td><td><span class="badge '+z[1]+'">'+z[0]+'</span></td></tr>'}).join(''):'<tr><td colspan="8">Nenhum aluno nesta turma.</td></tr>'}
  window.saveGrades=async function(){const d=db(),p=+(document.getElementById('gradePeriod')?.value||1),sub=document.getElementById('gradeSubject')?.value;if(!d||!sub)return;if(p===1||p===2&&sub!=='Português'){alert(p===1?'O 1º bimestre está fechado.':'O 2º bimestre está fechado para esta matéria.');return;}document.querySelectorAll('.gradeInput:not(:disabled)').forEach(i=>{const s=d.students.find(x=>String(x.id)===String(i.dataset.id));if(!s)return;s.grades??={};s.grades[p]??={};s.grades[p][sub]??={};s.grades[p][sub][i.dataset.k]=i.value===''?'':Number(i.value)});try{await window.save();renderGrades4();window.renderAll?.();window.toast?.('Notas salvas com sucesso!')}catch(e){alert(e.message||'Não foi possível salvar as notas.')}}
  function apply(){patchPeriodUI();renderGrades4()}
  window.addEventListener('load',()=>setTimeout(apply,350));window.addEventListener('DOMContentLoaded',()=>setTimeout(apply,250));setTimeout(apply,900);
})();
