(function(){
  const SUBJECTS=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const D=()=>window.__horizonte?.db||window.db;
  const students=()=>D()?.students||[];
  const classes=()=>D()?.classes||[];
  const subjects=()=>D()?.subjects||SUBJECTS;
  const go=page=>{document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo(0,0)};
  const rawAvg=(s,p,sub)=>{const g=s?.grades?.[p]?.[sub]||{};const a=['n1','n2','n3','n4'].map(k=>g[k]).filter(v=>v!==''&&v!=null&&!Number.isNaN(Number(v))).map(Number);return a.length?a.reduce((x,y)=>x+y,0)/3:null};
  const avg=(s,p,sub)=>{const o=s?.recoveryOverrides?.[p]?.[sub];return o!=null?Number(o):rawAvg(s,p,sub)};
  const status=m=>m==null?'Sem nota':m<6?'Recuperação':'Aprovado';
  const statusClass=m=>m==null?'neutral':m<6?'rec':'ok';
  function profilePage(){let p=document.getElementById('alunoPerfil');if(!p){p=document.createElement('section');p.id='alunoPerfil';p.className='page';document.querySelector('main')?.appendChild(p)}return p}
  function profile(s){if(!s)return;const p=profilePage(),c=classes().find(x=>String(x.id)===String(s.class))||{};let recovery=[];for(let u=1;u<=3;u++)for(const sub of subjects()){const m=avg(s,u,sub),r=s.recoveryResults?.[u]?.[sub];if(r||((m!=null)&&m<6))recovery.push({u,sub,m,status:r?.status||'recuperacao',recovery:r})}p.innerHTML='<div class="head"><div><h2>Perfil do aluno</h2><p>Informações acadêmicas, boletim e recuperação.</p></div><button class="outline" id="profileBack">← Voltar para Alunos</button></div><div class="grid2"><div class="panel"><div class="pad"><h3 style="margin:0 0 12px">Dados do aluno</h3><p><b>Nome:</b> '+esc(s.name)+'</p><p><b>Idade:</b> '+esc(s.age??s.idade??'—')+'</p><p><b>Turma:</b> '+esc(c.name||s.class||'—')+'</p><p><b>Unidade:</b> '+esc(c.unit||s.unit||'—')+'</p><p><b>Matrícula:</b> '+esc(s.id)+'</p></div></div><div class="panel"><div class="pad"><h3 style="margin:0 0 12px">Acesso rápido</h3><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="gold" id="profileReport">📄 Boletim</button><button class="gold" id="profileFreq">📅 Frequência</button><button class="gold" id="profileGrades">📝 Lançar notas</button><button class="gold" id="profileRec">🛟 Recuperação</button></div></div></div></div><div class="panel" style="margin-top:15px"><div class="ph"><b>Boletim — todas as unidades</b></div><div class="wrap"><table><thead><tr><th>Matéria</th><th>1ª Unidade</th><th>2ª Unidade</th><th>3ª Unidade</th><th>Situação</th></tr></thead><tbody>'+subjects().map(sub=>{const vals=[1,2,3].map(u=>avg(s,u,sub));const cur=vals.filter(v=>v!=null).pop();return '<tr><td><b>'+esc(sub)+'</b></td>'+vals.map(v=>'<td>'+(v==null?'—':Number(v).toFixed(2))+'</td>').join('')+'<td><span class="badge '+statusClass(cur)+'">'+status(cur)+'</span></td></tr>'}).join('')+'</tbody></table></div></div><div class="panel" style="margin-top:15px"><div class="ph"><b>Recuperações por matéria</b></div><div class="wrap"><table><thead><tr><th>Unidade</th><th>Matéria</th><th>Média aplicada</th><th>Situação</th></tr></thead><tbody>'+((recovery.map(r=>'<tr><td>'+r.u+'ª Unidade</td><td><b>'+esc(r.sub)+'</b></td><td>'+Number(r.m??r.recovery?.average??0).toFixed(2)+'</td><td><span class="badge '+(r.status==='aprovado'?'ok':r.status==='reprovado'?'bad':'rec')+'">'+(r.status==='aprovado'?'Aprovado':r.status==='reprovado'?'Reprovado':'Recuperação')+'</span></td></tr>').join(''))||'<tr><td colspan="4">Nenhuma matéria em recuperação.</td></tr>')+'</tbody></table></div></div>';p.querySelector('#profileBack').onclick=()=>go('alunos');p.querySelector('#profileReport').onclick=()=>{go('boletins');const sel=document.getElementById('reportStudent');if(sel){sel.value=s.id;sel.dispatchEvent(new Event('change',{bubbles:true}))}};p.querySelector('#profileFreq').onclick=()=>go('frequencia');p.querySelector('#profileGrades').onclick=()=>go('notas');p.querySelector('#profileRec').onclick=()=>go('recuperacao');go('alunoPerfil')}
  function bindStudentTable(){const tb=document.getElementById('studentTable');if(!tb||tb.dataset.profileDelegated==='1')return;tb.dataset.profileDelegated='1';tb.addEventListener('click',e=>{const tr=e.target.closest('tr');if(!tr)return;const id=(tr.querySelector('td:nth-child(4)')?.textContent||'').trim();const name=(tr.querySelector('td')?.textContent||'').trim().split('\n')[0].trim();const s=students().find(x=>String(x.id)===id)||students().find(x=>String(x.name).trim()===name);if(s){e.preventDefault();profile(s)}});}
  function enhanceRecovery(){const page=document.getElementById('recuperacao');if(!page)return false;if(page.dataset.navEnhanced==='1')return true;page.dataset.navEnhanced='1';const table=document.getElementById('recoveryTable');if(table&&!table.dataset.profileDelegated){table.dataset.profileDelegated='1';table.addEventListener('click',e=>{const cell=e.target.closest('td:first-child');if(!cell)return;const id=(cell.textContent||'').match(/\b\d{4}\b/)?.[0];const s=students().find(x=>String(x.id)===id);if(s)profile(s)})}return true}
  document.addEventListener('click',e=>{const n=e.target.closest?.('.nav[data-page]');if(!n)return;e.preventDefault();go(n.dataset.page);setTimeout(()=>{bindStudentTable();enhanceRecovery()},0)});
  document.addEventListener('input',e=>{if(e.target.id==='studentSearch')setTimeout(bindStudentTable,0)});
  function boot(){bindStudentTable();enhanceRecovery()}
  window.hzGo=go;window.hzOpenStudentProfile=profile;window.addEventListener('load',()=>setTimeout(boot,500));setTimeout(boot,900);setTimeout(boot,1800);setTimeout(boot,3000);
})();