(function(){
  const SUBJECTS=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  function D(){return window.__horizonte?.db||window.db}
  function avg(g){const a=['n1','n2','n3','n4'].map(k=>g?.[k]).filter(v=>v!==''&&v!=null&&!Number.isNaN(Number(v))).map(Number);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function unitAvg(s,p){const a=SUBJECTS.map(sub=>avg(s.grades?.[p]?.[sub]||{})).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function sit(m){return m==null?['Sem nota','neutral']:m>=6?['Aprovado','ok']:m>=5?['Recuperação','rec']:['Reprovado','bad']}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function patchPeriod(per){if(!per)return;const v=per.value;const wanted='<option value="1">1º Bimestre — Fechado</option><option value="2">2º Bimestre — Aberto</option><option value="3">3º Bimestre — Aberto</option>';if(per.innerHTML!==wanted)per.innerHTML=wanted;if(v==='2'||v==='3')per.value=v;}
  function patchHeader(table){const tr=table?.closest('table')?.querySelector('thead tr');if(!tr)return;tr.innerHTML='<th>Aluno</th><th>Nota 1</th><th>Nota 2</th><th>Nota 3</th><th>Nota 4</th><th>Média da Disciplina</th><th>Média da Unidade</th><th>Situação</th>';}
  function render(){const d=D(),table=document.getElementById('gradeTable'),cl=document.getElementById('gradeClass'),sub=document.getElementById('gradeSubject'),per=document.getElementById('gradePeriod');if(!d||!Array.isArray(d.students)||!table||!cl||!sub||!per)return;patchPeriod(per);patchHeader(table);const p=Number(per.value),subject=sub.value,students=d.students.filter(x=>x.class===cl.value);table.innerHTML=students.map(s=>{const g=s.grades?.[p]?.[subject]||{},m=avg(g),u=unitAvg(s,p),z=sit(m);return '<tr><td><b>'+esc(s.name)+'</b><br><small>'+esc(s.id)+'</small></td>'+['n1','n2','n3','n4'].map(k=>'<td><input class="gi" data-id="'+esc(s.id)+'" data-k="'+k+'" type="number" min="0" max="10" step=".1" value="'+(g[k]??'')+'" '+(p===1?'disabled':'')+'></td>').join('')+'<td>'+(m==null?'—':m.toFixed(1))+'</td><td><strong>'+(u==null?'—':u.toFixed(1))+'</strong></td><td><span class="badge '+z[1]+'">'+z[0]+'</span></td></tr>'}).join('')||'<tr><td colspan="8">Nenhum aluno.</td></tr>'}
  window.renderGrades=render;
  window.saveGrades=async function(){const d=D(),per=document.getElementById('gradePeriod'),sub=document.getElementById('gradeSubject');if(!d||!per||!sub)return;const p=Number(per.value);if(p===1)return window.toast?toast('O 1º bimestre está fechado.'):alert('O 1º bimestre está fechado.');document.querySelectorAll('#gradeTable .gi').forEach(i=>{const s=d.students.find(x=>String(x.id)===String(i.dataset.id));if(!s)return;s.grades??={};s.grades[p]??={};s.grades[p][sub.value]??={};s.grades[p][sub.value][i.dataset.k]=i.value===''?'':Number(i.value)});try{await window.save();render();window.toast&&toast('Notas salvas com sucesso! A média da unidade foi recalculada.')}catch(e){alert(e.message||'Não foi possível salvar as notas.')}};
  function boot(){const d=D();if(!d||!Array.isArray(d.students)){return setTimeout(boot,300)}const per=document.getElementById('gradePeriod');patchPeriod(per);if(per&&!per.dataset.horizonteChange){per.dataset.horizonteChange='1';per.addEventListener('change',()=>setTimeout(render,0))}render();}
  setTimeout(boot,1200);setTimeout(boot,3000);setTimeout(boot,6000);
})();
