(function(){
  const SUBJECTS=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  const MAX=[6,5,10,9];
  const SECOND_UNIT_NOTES={1001:[4.5,3.1,7.8,4.7],1002:[3.3,4,3.4,8.2],1003:[4,5.4,7.1,6],1004:[2.8,2.5,5.6,7.1],1005:[3.5,1.2,8.8,4.3],1006:[4.5,5.6,4.4,2.3],1007:[2.8,2.7,5.6,5],1008:[5.1,7.7,7,8.8],1009:[3.4,4.6,7,2.1],1010:[2.5,4,8.2,1.3],1011:[4.6,3.5,3.3,1.9],1012:[5.6,4,3.3,5.8],1013:[2.7,2.1,1.1,5.3],1014:[4.3,3.1,4.5,7.1],1015:[5,1.7,3.2,4.4],1016:[1.4,2.3,6.7,5.9],1017:[1.1,.9,3.1,.7],1018:[1.2,1.4,2,8.8],1019:[2.2,1.2,7.7,5.6],1020:[1.1,.7,5.6,8],1021:[5.3,5.6,8.9,7.4],1022:[4,5.1,4.3,6],1023:[3.5,5.3,4,4.5],1024:[1.1,2.3,1.8,8.9],1025:[4.7,6.7,6.2,5.4]};
  function D(){return window.__horizonte?.db||window.db}
  function total(g){const a=['n1','n2','n3','n4'].map(k=>g?.[k]).filter(v=>v!==''&&v!=null&&!Number.isNaN(Number(v))).map(Number);return a.length?a.reduce((x,y)=>x+y,0):null}
  function avg(g){const t=total(g);return t==null?null:t/3}
  function unitAvg(s,p){const a=SUBJECTS.map(sub=>avg(s.grades?.[p]?.[sub]||{})).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function sit(unit,subjectTotal,manual){if(manual==='aprovado')return['Aprovado','ok'];if(manual==='recuperacao')return['Recuperação','rec'];if(manual==='reprovado')return['Reprovado','bad'];if(subjectTotal==null||unit==null)return['Sem nota','neutral'];return subjectTotal>=15?['Aprovado','ok']:['Recuperação','rec']}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  async function seedSecondUnit(d){let changed=false;for(const [id,vals] of Object.entries(SECOND_UNIT_NOTES)){const s=d.students.find(x=>String(x.id)===String(id));if(!s)continue;s.grades??={};s.grades[2]??={};s.grades[2].Português??={};const g=s.grades[2].Português;const keys=['n1','n2','n3','n4'];keys.forEach((k,i)=>{if(g[k]!==vals[i]){g[k]=vals[i];changed=true}})}if(changed&&typeof window.save==='function'){try{await window.save()}catch(e){console.warn('Não foi possível salvar automaticamente as notas da 2ª unidade.',e)}}}
  function patchPeriod(per){if(!per)return;const v=per.value;const wanted='<option value="1">1º Bimestre — Fechado</option><option value="2">2º Bimestre — Aberto</option><option value="3">3º Bimestre — Aberto</option>';if(per.innerHTML!==wanted)per.innerHTML=wanted;if(v==='2'||v==='3')per.value=v;}
  function patchHeader(table){const tr=table?.closest('table')?.querySelector('thead tr');if(!tr)return;tr.innerHTML='<th>Aluno</th><th>Nota 1 <small>(6)</small></th><th>Nota 2 <small>(5)</small></th><th>Nota 3 <small>(10)</small></th><th>Nota 4 <small>(9)</small></th><th>Total / 30</th><th>Média da Disciplina</th><th>Média da Unidade</th><th>Situação</th>';}
  function injectStatusPanel(cl){let panel=document.getElementById('studentStatusPanel');if(!panel){panel=document.createElement('section');panel.id='studentStatusPanel';panel.style.cssText='margin:0 0 16px;padding:16px;border:1px solid #dbe3f0;border-radius:14px;background:#fff;box-shadow:0 4px 14px rgba(15,23,42,.06)';const table=document.getElementById('gradeTable');if(table)table.parentNode.insertBefore(panel,table.closest('table')||table)}const students=(D()?.students||[]).filter(x=>x.class===cl.value);const old=document.getElementById('gradeStudentStatus')?.value||'';panel.innerHTML='<div style="font-weight:800;font-size:16px;margin-bottom:10px">Situação do Aluno</div><div style="font-size:13px;color:#64748b;margin-bottom:10px">Escolha o aluno e defina a situação manualmente.</div><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><select id="gradeStudentStatus" style="min-width:250px;padding:9px 11px;border:1px solid #cbd5e1;border-radius:9px;background:#fff"><option value="">Selecione o aluno...</option>'+students.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+' — '+esc(s.id)+'</option>').join('')+'</select><button type="button" id="statusApprove" style="padding:9px 13px;border:0;border-radius:9px;background:#15803d;color:#fff;font-weight:700;cursor:pointer">✓ Aprovar aluno</button><button type="button" id="statusRecovery" style="padding:9px 13px;border:0;border-radius:9px;background:#d97706;color:#fff;font-weight:700;cursor:pointer">↻ Recuperação</button><button type="button" id="statusFail" style="padding:9px 13px;border:0;border-radius:9px;background:#be123c;color:#fff;font-weight:700;cursor:pointer">✕ Reprovar aluno</button></div><div id="studentStatusCurrent" style="margin-top:10px;font-size:13px;color:#64748b"></div>';
    const sel=document.getElementById('gradeStudentStatus');if(old&&students.some(s=>String(s.id)===String(old)))sel.value=old;
    function showCurrent(){const s=students.find(x=>String(x.id)===String(sel.value));const manual=s?.manualStatus;const u=s?unitAvg(s,Number(document.getElementById('gradePeriod')?.value||2)):null;document.getElementById('studentStatusCurrent').textContent=s?(manual?'Situação manual: '+({aprovado:'Aprovado',recuperacao:'Recuperação',reprovado:'Reprovado'}[manual]||manual):'Situação automática da unidade: '+(u!=null?(u>=5?'Aprovado':'Recuperação'):'Sem nota')):''}
    async function setStatus(v){const s=students.find(x=>String(x.id)===String(sel.value));if(!s)return window.toast?toast('Selecione um aluno primeiro.'):alert('Selecione um aluno primeiro.');const oldStatus=s.manualStatus;s.manualStatus=v;try{await window.save();render();window.toast&&toast('Situação do aluno salva com sucesso!')}catch(e){s.manualStatus=oldStatus;alert(e.message||'Não foi possível salvar a situação do aluno.')}}
    sel.onchange=showCurrent;document.getElementById('statusApprove').onclick=()=>setStatus('aprovado');document.getElementById('statusRecovery').onclick=()=>setStatus('recuperacao');document.getElementById('statusFail').onclick=()=>setStatus('reprovado');showCurrent();
  }
  function render(){const d=D(),table=document.getElementById('gradeTable'),cl=document.getElementById('gradeClass'),sub=document.getElementById('gradeSubject'),per=document.getElementById('gradePeriod');if(!d||!Array.isArray(d.students)||!table||!cl||!sub||!per)return;patchPeriod(per);patchHeader(table);injectStatusPanel(cl);const p=Number(per.value),subject=sub.value,students=d.students.filter(x=>x.class===cl.value);table.innerHTML=students.map(s=>{const g=s.grades?.[p]?.[subject]||{},t=total(g),m=avg(g),u=unitAvg(s,p),z=sit(u,t,s.manualStatus);return '<tr><td><b>'+esc(s.name)+'</b><br><small>'+esc(s.id)+'</small></td>'+['n1','n2','n3','n4'].map((k,i)=>'<td><input class="gi" data-id="'+esc(s.id)+'" data-k="'+k+'" type="number" min="0" max="'+MAX[i]+'" step=".1" value="'+(g[k]??'')+'" '+(p===1?'disabled':'')+'></td>').join('')+'<td><strong>'+(t==null?'—':t.toFixed(1))+' / 30</strong></td><td><strong>'+(m==null?'—':m.toFixed(2))+'</strong></td><td><strong>'+(u==null?'—':u.toFixed(2))+'</strong></td><td><span class="badge '+z[1]+'">'+z[0]+'</span></td></tr>'}).join('')||'<tr><td colspan="9">Nenhum aluno.</td></tr>'}
  window.renderGrades=render;
  window.saveGrades=async function(){const d=D(),per=document.getElementById('gradePeriod'),sub=document.getElementById('gradeSubject');if(!d||!per||!sub)return;const p=Number(per.value);if(p===1)return window.toast?toast('O 1º bimestre está fechado.'):alert('O 1º bimestre está fechado.');document.querySelectorAll('#gradeTable .gi').forEach(i=>{const s=d.students.find(x=>String(x.id)===String(i.dataset.id));if(!s)return;s.grades??={};s.grades[p]??={};s.grades[p][sub.value]??={};s.grades[p][sub.value][i.dataset.k]=i.value===''?'':Number(i.value)});try{await window.save();render();window.toast&&toast('Notas salvas! Cada nota respeita seu valor máximo: 6, 5, 10 e 9.')}catch(e){alert(e.message||'Não foi possível salvar as notas.')}}
  async function boot(){const d=D();if(!d||!Array.isArray(d.students)){return setTimeout(boot,300)}await seedSecondUnit(d);const per=document.getElementById('gradePeriod');patchPeriod(per);if(per&&!per.dataset.horizonteChange){per.dataset.horizonteChange='1';per.addEventListener('change',()=>setTimeout(render,0))}render();}
  setTimeout(boot,1200);setTimeout(boot,3000);setTimeout(boot,6000);
})();
