(function(){
  const SUBJECTS=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
  function D(){return window.__horizonte?.db||window.db}
  function avg(g){const a=['n1','n2','n3','n4'].map(k=>g?.[k]).filter(v=>v!==''&&v!=null&&!Number.isNaN(Number(v))).map(Number);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function sit(m){return m==null?['Sem nota','neutral']:m>=6?['Aprovado','ok']:m>=5?['Recuperação','rec']:['Reprovado','bad']}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function render(){const d=D(),table=document.getElementById('gradeTable'),cl=document.getElementById('gradeClass'),sub=document.getElementById('gradeSubject'),per=document.getElementById('gradePeriod');if(!d||!table||!cl||!sub||!per)return;per.innerHTML='<option value="1">1º Bimestre — Fechado</option><option value="2">2º Bimestre — Aberto</option><option value="3">3º Bimestre — Aberto</option>';const p=Number(per.value),subject=sub.value,students=d.students.filter(x=>x.class===cl.value);table.innerHTML=students.map(s=>{const g=s.grades?.[p]?.[subject]||{},m=avg(g),z=sit(m);return '<tr><td><b>'+esc(s.name)+'</b><br><small>'+s.id+'</small></td>'+['n1','n2','n3','n4'].map(k=>'<td><input class="gi" data-id="'+s.id+'" data-k="'+k+'" type="number" min="0" max="10" step=".1" value="'+(g[k]??'')+'"></td>').join('')+'<td>'+(m==null?'—':m.toFixed(1))+'</td><td><span class="badge '+z[1]+'">'+z[0]+'</span></td></tr>'}).join('')||'<tr><td colspan="7">Nenhum aluno.</td></tr>'}
  window.renderGrades=render;
  window.saveGrades=async function(){const d=D(),per=document.getElementById('gradePeriod'),sub=document.getElementById('gradeSubject');if(!d||!per||!sub)return;const p=Number(per.value);if(p===1)return (window.toast?toast('O 1º bimestre está fechado.'):alert('O 1º bimestre está fechado.'));d.students.filter(s=>s.grades?.[2]).forEach(s=>{});document.querySelectorAll('#gradeTable .gi').forEach(i=>{const s=d.students.find(x=>String(x.id)===String(i.dataset.id));if(!s)return;s.grades??={};s.grades[p]??={};s.grades[p][sub.value]??={};s.grades[p][sub.value][i.dataset.k]=i.value===''?'':Number(i.value)});try{await window.save();render();window.toast&&toast('Notas salvas com sucesso!')}catch(e){alert(e.message||'Não foi possível salvar as notas.')}};
  function start(){const d=D();if(!d||!Array.isArray(d.students))return;d.students.forEach(s=>{if(s.grades?.[2]&&Object.keys(s.grades[2]).length)delete s.grades[2]});d.stateVersion=3;render()}
  window.addEventListener('load',()=>setTimeout(start,1800));setTimeout(start,3000);
})();
