(function(){
const S=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
const E=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function D(){return window.__horizonte?.db||window.db} function save(){return window.save?window.save():Promise.resolve()}
function questions(subject,topic,n){let out=[];for(let i=1;i<=n;i++){let k=(i-1)%8;let type=['conceito','aplicação','interpretação','análise','relação','exemplo','revisão','desafio'][k];let q=`${i}. Em ${subject}, considerando o assunto “${topic}”, qual alternativa melhor representa uma questão de ${type} sobre esse conteúdo?`;let correct=`Aplicação correta dos conceitos de ${topic}`;let opts=[correct,`Uma afirmação sem relação com ${topic}`,`Uma conclusão contrária ao conteúdo de ${topic}`,`Nenhuma das alternativas`];let sh=(i*3)%4;opts=opts.slice(sh).concat(opts.slice(0,sh));out.push({n:i,q,opts,correct})}return out}
function nav(){let a=document.querySelector('aside');if(!a)return;if(!a.querySelector('[data-page="recuperacao"]')){let b=[...a.querySelectorAll('.nav')].find(x=>x.dataset.page==='boletins');b?.insertAdjacentHTML('afterend','<button class="nav" data-page="recuperacao">🎯 Recuperação</button><button class="nav" data-page="provas">📚 Provas</button>')}}
function ui(){let main=document.querySelector('main');if(!main||document.getElementById('provasV2'))return;main.insertAdjacentHTML('beforeend',`<section id="recuperacao" class="page"><div class="head"><div><h2>Recuperação — Simulados</h2><p>Simulado exclusivo: 60 questões, valendo 7,0 pontos.</p></div></div><div class="filters"><select id="rUnit"></select><select id="rClass"></select><select id="rStudent"></select><select id="rSubject"></select><select id="rPeriod"><option value="1">1º Bimestre</option><option value="2">2º Bimestre</option></select><input id="rTopic" placeholder="Assunto da recuperação" style="min-width:260px"><button class="gold" id="rGen">Gerar simulado</button></div><div id="rBox" class="panel"></div></section><section id="provasV2" class="page"><div class="head"><div><h2>Provas</h2><p>Provas da unidade: 25 questões, valendo 10,0 pontos.</p></div></div><div class="filters"><select id="pUnit"></select><select id="pClass"></select><select id="pSubject"></select><input id="pTopic" placeholder="Assunto da prova" style="min-width:260px"><button class="gold" id="pGen">Gerar prova</button><button class="btn" id="pAll">Gerar todas as 48 provas</button></div><div id="pBox" class="panel"></div></section>`)}
function fill(id,a){let e=document.getElementById(id);if(e)e.innerHTML=a.map(x=>`<option value="${E(x.value??x)}">${E(x.label??x)}</option>`).join('')}
function classes(id,u){let d=D();fill(id,d.classes.filter(c=>c.unit===u).map(c=>({value:c.id,label:c.name})))}
function students(){let d=D(),c=document.getElementById('rClass')?.value;fill('rStudent',d.students.filter(s=>s.class===c).map(s=>({value:s.id,label:s.name+' — '+s.id})))}
function setup(){let d=D();if(!d)return;fill('rUnit',d.units);fill('pUnit',d.units);fill('rSubject',S.map(x=>({value:x,label:x})));fill('pSubject',S.map(x=>({value:x,label:x})));classes('rClass',d.units[0]);classes('pClass',d.units[0]);students();document.getElementById('rUnit').onchange=e=>{classes('rClass',e.target.value);students()};document.getElementById('pUnit').onchange=e=>classes('pClass',e.target.value);document.getElementById('rClass').onchange=students;document.getElementById('rGen').onclick=()=>genRecovery();document.getElementById('pGen').onclick=()=>genRegular();document.getElementById('pAll').onclick=()=>genAll()}
function ensure(){let d=D();d.exams??=[];return d}
function genRecovery(){let d=ensure(),s=d.students.find(x=>x.id===document.getElementById('rStudent').value),sub=document.getElementById('rSubject').value,topic=document.getElementById('rTopic').value.trim();if(!s||!topic)return alert('Selecione o aluno, a matéria e informe o assunto.');let p=+document.getElementById('rPeriod').value;let ex={id:'REC-'+s.id+'-'+p+'-'+sub+'-'+Date.now(),type:'recovery',student:s.id,studentName:s.name,class:s.class,period:p,subject:sub,topic,points:7,questions:questions(sub,topic,60),createdAt:new Date().toISOString()};d.exams.push(ex);render(ex);save().then(()=>window.toast?.('Simulado de recuperação salvo.'))}
function genRegular(){let d=ensure(),c=document.getElementById('pClass').value,sub=document.getElementById('pSubject').value,topic=document.getElementById('pTopic').value.trim();if(!topic)return alert('Informe o assunto da prova.');let ex={id:'EX-'+c+'-'+sub+'-'+Date.now(),type:'regular',class:c,subject:sub,topic,points:10,questions:questions(sub,topic,25),createdAt:new Date().toISOString()};d.exams.push(ex);render(ex);save().then(()=>window.toast?.('Prova salva.'))}
function genAll(){let d=ensure(),topic=prompt('Assunto geral das 48 provas:');if(!topic)return;for(let c of d.classes)for(let sub of S){let ex={id:'EX-'+c.id+'-'+sub.replace(/\\W/g,'')+'-'+Date.now(),type:'regular',class:c.id,subject:sub,topic,points:10,questions:questions(sub,topic,25),createdAt:new Date().toISOString()};d.exams.push(ex)}renderList();save().then(()=>window.toast?.('48 provas geradas.'))}
function print(ex){let c=D().classes.find(x=>x.id===ex.class);let h=`<html><head><title>${E(ex.type==='recovery'?'Simulado de Recuperação':'Prova')}</title><style>@page{margin:18mm}body{font-family:Arial;color:#111}header{text-align:center;border-bottom:2px solid #173f6d;padding-bottom:12px;margin-bottom:16px}header img{width:150px;height:86px;object-fit:contain}.fields{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px;margin:10px 0 20px}.line{border-bottom:1px solid #555;min-height:20px}.q{margin:14px 0;break-inside:avoid}.q div{margin:5px 0}</style></head><body><header><img src="${location.origin}/logo-colegio.svg"><h2>COLÉGIO HORIZONTE</h2><b>${E(ex.type==='recovery'?'SIMULADO DE RECUPERAÇÃO':'PROVA DA UNIDADE')}</b></header><div class="fields"><div>Nome do aluno: <span class="line">${E(ex.studentName||'')}</span></div><div>Data: <span class="line">____/____/______</span></div><div>Matéria: <span class="line">${E(ex.subject)}</span></div><div>Série/Turma: <span class="line">${E(c?.name||ex.class)}</span></div><div>Professor(a): <span class="line">________________</span></div><div>Matrícula: <span class="line">${E(ex.student||'')}</span></div></div><p><b>Assunto:</b> ${E(ex.topic)} &nbsp; <b>Valor:</b> ${ex.points.toFixed(1).replace('.',',')} pontos &nbsp; <b>Questões:</b> ${ex.questions.length}</p>${ex.questions.map(q=>`<div class="q"><b>${q.n}. ${E(q.q)}</b>${q.opts.map((o,i)=>`<div>${String.fromCharCode(65+i)}) ${E(o)}</div>`).join('')}</div>`).join('')}</body></html>`;let w=window.open('','_blank');w.document.write(h);w.document.close();setTimeout(()=>w.print(),300)}
function render(ex){let box=document.getElementById(ex.type==='recovery'?'rBox':'pBox');if(!box)return;box.innerHTML=`<div class="pad"><b>${E(ex.type==='recovery'?'Simulado de Recuperação':'Prova da Unidade')}</b><p>${E(ex.subject)} · ${E(ex.topic)} · ${ex.questions.length} questões · ${ex.points.toFixed(1).replace('.',',')} pontos</p><button class="gold" id="printNow">Gerar PDF / Imprimir</button></div>`;document.getElementById('printNow').onclick=()=>print(ex)}
function renderList(){let d=D(),box=document.getElementById('pBox');if(!box)return;box.innerHTML='<div class="pad"><b>Provas armazenadas</b><div class="grid2">'+(d.exams||[]).filter(x=>x.type==='regular').slice(-60).map(e=>`<div class="tile"><b>${E(e.subject)}</b><br>${E(e.topic)}<br>${E(d.classes.find(c=>c.id===e.class)?.name||e.class)} · 25 questões · 10,0 pontos<br><button class="btn" data-ex="${E(e.id)}">Abrir</button></div>`).join('')+'</div></div>';box.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>render(d.exams.find(x=>x.id===b.dataset.ex)))}
function patch(){nav();ui();setup();renderList()}function hook(){patch();let old=window.showApp;if(old&&!old.__pv2){let f=old;window.showApp=async function(){let r=f.apply(this,arguments);setTimeout(patch,100);return r};window.showApp.__pv2=true}}window.addEventListener('load',()=>setTimeout(hook,300));setTimeout(hook,800);})();