(function(){
const S=['Português','Matemática','História','Geografia','Biologia','Física','Química','Inglês'];
const E=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function D(){return window.__horizonte?.db||window.db} function save(){return window.save?window.save():Promise.resolve()}
const BANK={
'Português':['Analise a construção sintática do período e assinale a interpretação mais precisa.','Em um texto argumentativo, avalie o efeito de sentido produzido pela escolha vocabular.','Compare duas construções e identifique a que preserva norma-padrão sem alterar o sentido.','A partir do contexto, infira a relação entre coesão, coerência e progressão temática.','Reescreva mentalmente o trecho e identifique a alternativa que mantém sentido, regência e concordância.','Examine a função discursiva do recurso linguístico apresentado e escolha a análise adequada.'],
'Matemática':['Resolva o problema usando propriedades algébricas e escolha o resultado correto.','Analise a expressão e determine qual transformação preserva sua equivalência.','Um estudante apresentou uma solução. Identifique o passo em que o raciocínio pode ser validado.','A situação envolve proporção, função ou geometria. Determine a estratégia mais eficiente.','Compare os resultados possíveis e identifique o único compatível com todas as condições.','Generalize o padrão apresentado e escolha a expressão que o representa.'],
'História':['Analise a relação de causa e consequência entre os acontecimentos apresentados.','Compare perspectivas históricas e identifique a interpretação sustentada pelas evidências.','Uma fonte histórica apresenta determinado contexto. Avalie o que ela permite concluir.','Relacione transformações políticas, econômicas e sociais e assinale a síntese correta.','Identifique a permanência e a mudança presentes no processo histórico.','Avalie criticamente uma afirmação sobre o período e escolha a conclusão mais consistente.'],
'Geografia':['Analise a relação entre território, sociedade e dinâmica espacial apresentada.','Interprete os dados e identifique a consequência geográfica mais plausível.','Compare escalas de análise e escolha a explicação adequada para o fenômeno.','Relacione fatores naturais e humanos sem confundir causa, correlação e consequência.','A partir do espaço descrito, identifique o conceito geográfico que melhor explica o fenômeno.','Avalie uma política territorial e identifique seu possível impacto espacial.'],
'Biologia':['Analise o processo biológico e identifique a sequência correta de eventos.','Relacione estrutura e função e escolha a alternativa biologicamente consistente.','Compare dois sistemas e determine a consequência de uma alteração em um deles.','Interprete os dados de um experimento e identifique a hipótese mais adequada.','Explique a relação entre níveis de organização biológica no caso apresentado.','Avalie uma afirmação e identifique a conclusão sustentada pelos mecanismos biológicos.'],
'Física':['Analise as grandezas envolvidas e determine a relação física correta.','Resolva a situação aplicando a lei ou princípio adequado e verifique as unidades.','Compare dois cenários e identifique como a alteração de uma grandeza afeta as demais.','Interprete o gráfico ou descrição e determine o comportamento físico correspondente.','Avalie o raciocínio de um estudante e identifique a conclusão compatível com as leis físicas.','Combine duas relações físicas e determine a consequência quantitativa ou conceitual.'],
'Química':['Analise partículas, propriedades e transformações e escolha a explicação correta.','Relacione representação microscópica e fenômeno macroscópico apresentado.','Compare substâncias e determine a propriedade que explica o comportamento observado.','Interprete uma reação e identifique reagentes, produtos e conservação relevante.','Avalie uma hipótese experimental e escolha a conclusão compatível com os dados.','Relacione estrutura, propriedades e transformações químicas no contexto apresentado.'],
'Inglês':['Read the context and identify the interpretation that best preserves meaning.','Analyze the grammatical structure and choose the form that fits the context.','Compare the alternatives and identify the one that is grammatically and semantically appropriate.','Infer the meaning of the expression from context and choose the best interpretation.','Rewrite the sentence mentally and identify the option that keeps the original meaning.','Analyze the communicative purpose and choose the most appropriate language use.']};
function makeQuestions(sub,topic,n,seed=7){let b=BANK[sub]||BANK.Português,out=[];for(let i=0;i<n;i++){let j=(i+seed)%b.length;let stem=b[j]+' Considere especificamente o assunto “'+topic+'” e os conceitos relacionados a ele. Qual alternativa apresenta a análise mais correta e completa?';let correct='Aplicação rigorosa dos conceitos de '+topic+', com justificativa coerente com o contexto apresentado.';let wrong=[`Uma interpretação que ignora os conceitos centrais de ${topic}.`,`Uma conclusão baseada em informação incompatível com ${topic}.`,`Uma resposta absoluta sem considerar as condições do problema de ${topic}.`];let opts=[correct,...wrong],shift=(i*7+seed)%4;opts=opts.slice(shift).concat(opts.slice(0,shift));out.push({n:i+1,q:stem,opts,correct,subject:sub})}return out}
function mixedQuestions(subjects,topic,n,seed){let out=[];for(let i=0;i<n;i++){let sub=subjects[i%subjects.length];let qs=makeQuestions(sub,topic,1,seed+i*3);qs[0].n=i+1;out.push(qs[0])}return out}
function subjectAvg(s,p,sub){let g=s.grades?.[p]?.[sub]||{},a=['n1','n2','n3'].map(k=>g[k]).filter(v=>v!==''&&v!=null).map(Number).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function failedSubjects(s,p){return S.filter(sub=>{let v=subjectAvg(s,p,sub);return v!=null&&v<7})}
function nav(){let a=document.querySelector('aside');if(!a)return;if(!a.querySelector('[data-page="recuperacao"]')){let b=[...a.querySelectorAll('.nav')].find(x=>x.dataset.page==='boletins');b?.insertAdjacentHTML('afterend','<button class="nav" data-page="recuperacao">🎯 Recuperação</button><button class="nav" data-page="provas">📚 Provas</button>')}}
function ui(){let main=document.querySelector('main');if(!main||document.getElementById('provasV2'))return;main.insertAdjacentHTML('beforeend',`<section id="recuperacao" class="page"><div class="head"><div><h2>Recuperação — Simulado multidisciplinar</h2><p>Geração automática para todos os alunos que perderam uma ou mais matérias. 60 questões, valendo 7,0 pontos, distribuídas entre todas as matérias em recuperação.</p></div></div><div class="filters"><select id="rUnit"></select><select id="rClass"></select><select id="rPeriod"><option value="1">1º Bimestre</option><option value="2">2º Bimestre</option></select><input id="rTopic" placeholder="Assunto/base da recuperação" style="min-width:280px"><button class="gold" id="rGenAll">Gerar simulados de todos em recuperação</button></div><div id="rBox" class="panel"></div></section><section id="provasV2" class="page"><div class="head"><div><h2>Provas da unidade</h2><p>Prova difícil: exatamente 25 questões, valendo 10,0 pontos. Só é liberada após informar matéria e assunto.</p></div></div><div class="filters"><select id="pUnit"></select><select id="pClass"></select><select id="pSubject"></select><input id="pTopic" placeholder="Assunto da prova" style="min-width:280px"><button class="gold" id="pGen">Gerar prova difícil</button></div><div id="pBox" class="panel"></div></section>`)}
function fill(id,a){let e=document.getElementById(id);if(e)e.innerHTML=a.map(x=>`<option value="${E(x.value??x)}">${E(x.label??x)}</option>`).join('')}
function classes(id,u){let d=D();fill(id,(d.classes||[]).filter(c=>c.unit===u).map(c=>({value:c.id,label:c.name})))}
function setup(){let d=D();if(!d)return;fill('rUnit',d.units||[]);fill('pUnit',d.units||[]);fill('pSubject',S);classes('rClass',d.units?.[0]);classes('pClass',d.units?.[0]);document.getElementById('rUnit').onchange=e=>{classes('rClass',e.target.value);renderRecovery()};document.getElementById('pUnit').onchange=e=>classes('pClass',e.target.value);document.getElementById('rClass').onchange=renderRecovery;document.getElementById('rPeriod').onchange=renderRecovery;document.getElementById('rGenAll').onclick=genRecoveryAll;document.getElementById('pGen').onclick=genRegular}
function ensure(){let d=D();d.exams??=[];return d}
function genRecoveryAll(){let d=ensure(),p=+document.getElementById('rPeriod').value,c=document.getElementById('rClass').value,topic=document.getElementById('rTopic').value.trim();if(!topic)return alert('Informe o assunto/base da recuperação.');let students=(d.students||[]).filter(s=>s.class===c&&failedSubjects(s,p).length);if(!students.length)return alert('Não há alunos em recuperação nesta turma e bimestre.');let made=[];students.forEach((s,idx)=>{let failed=failedSubjects(s,p),id='REC-'+s.id+'-'+p;let ex={id,type:'recovery',student:s.id,studentName:s.name,class:s.class,period:p,subjects:failed,subject:failed.join(' + '),topic,points:7,questions:mixedQuestions(failed,topic,60,idx+p*11+failed.length*17),createdAt:new Date().toISOString()};d.exams=d.exams.filter(x=>x.id!==id);d.exams.push(ex);made.push(ex)});renderRecoveryList(made);save().then(()=>window.toast?.(`${made.length} simulado(s) de recuperação gerado(s).`))}
function genRegular(){let d=ensure(),c=document.getElementById('pClass').value,sub=document.getElementById('pSubject').value,topic=document.getElementById('pTopic').value.trim();if(!sub||!topic)return alert('Para gerar a prova, informe a matéria e o assunto.');let ex={id:'EX-'+c+'-'+sub.replace(/\W/g,'')+'-'+Date.now(),type:'regular',class:c,subject:sub,topic,points:10,questions:makeQuestions(sub,topic,25,c.length*13+sub.length*7),createdAt:new Date().toISOString()};d.exams.push(ex);render(ex);save().then(()=>window.toast?.('Prova difícil salva.'))}
function professorFor(ex){let d=D(),u=(d.users||[]).find(x=>x.role==='professor'&&x.subject===ex.subject);return u?.name||''}
function print(ex){let d=D(),c=d.classes.find(x=>x.id===ex.class),title=ex.type==='recovery'?'SIMULADO MULTIDISCIPLINAR DE RECUPERAÇÃO':'PROVA DA UNIDADE',subs=ex.subjects?.join(', ')||ex.subject;let h=`<html><head><title>${E(title)}</title><style>@page{margin:16mm}body{font-family:Arial,sans-serif;color:#111;font-size:12pt}header{text-align:center;border-bottom:2px solid #173f6d;padding-bottom:10px;margin-bottom:12px}header img{width:150px;height:75px;object-fit:contain}.fields{display:grid;grid-template-columns:2fr 1fr 1fr;gap:9px;margin:12px 0}.line{border-bottom:1px solid #555;display:inline-block;min-width:100px}.q{margin:14px 0;break-inside:avoid}.q div{margin:5px 0}.meta{border:1px solid #888;padding:8px;margin:10px 0 16px}</style></head><body><header><img src="${location.origin}/logo-colegio.svg" onerror="this.style.display='none'"><h2>COLÉGIO HORIZONTE</h2><b>${title}</b></header><div class="fields"><div>Nome do aluno: <span class="line">${E(ex.studentName||'')}</span></div><div>Data: <span class="line">____/____/______</span></div><div>Matéria: <span class="line">${E(subs)}</span></div><div>Série/Turma: <span class="line">${E(c?.name||ex.class)}</span></div><div>Professor(a): <span class="line">${E(professorFor(ex)||'________________')}</span></div><div>Matrícula: <span class="line">${E(ex.student||'')}</span></div></div><div class="meta"><b>Assunto:</b> ${E(ex.topic)} &nbsp; <b>Valor:</b> ${Number(ex.points).toFixed(1).replace('.',',')} pontos &nbsp; <b>Questões:</b> ${ex.questions.length}</div>${ex.questions.map(q=>`<div class="q"><b>${q.n}. [${E(q.subject||ex.subject)}] ${E(q.q)}</b>${q.opts.map((o,i)=>`<div>${String.fromCharCode(65+i)}) ${E(o)}</div>`).join('')}</div>`).join('')}</body></html>`;let w=window.open('','_blank');if(!w)return alert('Permita pop-ups para gerar o PDF.');w.document.write(h);w.document.close();setTimeout(()=>w.print(),500)}
function render(ex){let box=document.getElementById('pBox');if(!box)return;box.innerHTML=`<div class="pad"><b>${E(ex.type==='recovery'?'Simulado multidisciplinar de recuperação':'Prova difícil da unidade')}</b><p>${E(ex.subject)} · ${E(ex.topic)} · ${ex.questions.length} questões · ${Number(ex.points).toFixed(1).replace('.',',')} pontos</p><button class="gold" id="printNow">Gerar PDF / Imprimir</button></div>`;document.getElementById('printNow').onclick=()=>print(ex)}
function renderRecovery(){let d=D(),p=+document.getElementById('rPeriod')?.value||1,c=document.getElementById('rClass')?.value,s=(d?.students||[]).filter(x=>x.class===c&&failedSubjects(x,p).length),box=document.getElementById('rBox');if(!box)return;box.innerHTML=`<div class="pad"><b>${s.length} aluno(s) em recuperação</b><div class="grid2" style="margin-top:12px">${s.map(x=>`<div class="tile"><b>${E(x.name)}</b><br>Matrícula: ${E(x.id)}<br>Matérias perdidas: ${failedSubjects(x,p).map(z=>E(z)).join(', ')}<br><span class="muted">Simulado: 60 questões · 7,0 pontos</span></div>`).join('')||'<p>Nenhum aluno em recuperação nesta turma/bimestre.</p>'}</div></div>`}
function renderRecoveryList(es){let box=document.getElementById('rBox');if(!box)return;box.innerHTML='<div class="pad"><b>'+es.length+' simulado(s) gerado(s)</b><div class="grid2" style="margin-top:12px">'+es.map(e=>`<div class="tile"><b>${E(e.studentName)}</b><br>${E(e.subject)}<br>${E(e.topic)} · 60 questões · 7,0 pontos<br><button class="btn" data-rec="${E(e.id)}">Abrir / PDF</button></div>`).join('')+'</div></div>';box.querySelectorAll('[data-rec]').forEach(b=>b.onclick=()=>print((D().exams||[]).find(x=>x.id===b.dataset.rec)))}
function renderList(){let d=D(),box=document.getElementById('pBox');if(!box)return;let es=(d.exams||[]).filter(x=>x.type==='regular');box.innerHTML='<div class="pad"><b>Provas armazenadas</b><div class="grid2">'+es.slice(-60).map(e=>`<div class="tile"><b>${E(e.subject)}</b><br>${E(e.topic)}<br>${E(d.classes.find(c=>c.id===e.class)?.name||e.class)} · 25 questões · 10,0 pontos<br><button class="btn" data-ex="${E(e.id)}">Abrir / PDF</button></div>`).join('')+'</div></div>';box.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>render((d.exams||[]).find(x=>x.id===b.dataset.ex)))}
function patch(){nav();ui();setup();renderRecovery();renderList()}function hook(){patch();let old=window.showApp;if(old&&!old.__pv2){let f=old;window.showApp=async function(){let r=f.apply(this,arguments);setTimeout(patch,100);return r};window.showApp.__pv2=true}}window.addEventListener('load',()=>setTimeout(hook,300));setTimeout(hook,800);})();