const ADMIN={user:'joaopedroadmin',name:'João Pedro',role:'admin',hash:'9b6b5cf336a76742393239b8d6d94f3b8e82c602ff4303bfb7e6382ae55108f3'};
const TEACHER={user:'leticiaramos',name:'Léticia Ramos',role:'professor',hash:'7f0773073aa4ec31c7673d17380d72b9c71fbf3a2be41b7a2467156896823bfe'};
const STUDENT_PASS_HASH='f56f72ba4ab76e2b0e7f8d00dad60ff1dd41165d460dbff61d0e8afda466e54c';
async function hash(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function cookie(n,v,age){return `${n}=${v}; Max-Age=${age}; Path=/; HttpOnly; Secure; SameSite=Lax`}
async function me(request,env){const c=request.headers.get('Cookie')||'',m=c.match(/(?:^|;\s*)horizonte_session=([^;]+)/);if(m&&env.DB){const r=await env.DB.prepare('SELECT s.user,u.name,u.role FROM sessions s JOIN users u ON u.user=s.user WHERE s.token=? AND s.expires_at>?').bind(m[1],Math.floor(Date.now()/1000)).first();if(r)return r}return null}
async function ensure(env){if(!env.DB)throw Error('Banco de dados D1 não configurado.');await env.DB.batch([env.DB.prepare('CREATE TABLE IF NOT EXISTS users (user TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,pass_hash TEXT NOT NULL)'),env.DB.prepare('CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY,user TEXT NOT NULL,expires_at INTEGER NOT NULL)'),env.DB.prepare('CREATE TABLE IF NOT EXISTS app_state (id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)')]);await env.DB.prepare('INSERT OR IGNORE INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(ADMIN.user,ADMIN.name,ADMIN.role,ADMIN.hash).run();await env.DB.prepare('INSERT OR IGNORE INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(TEACHER.user,TEACHER.name,TEACHER.role,TEACHER.hash).run()}
async function studentFromState(env,id){let raw=null;const row=await env.DB.prepare('SELECT data FROM app_state WHERE id=1').first();if(row?.data)raw=row.data;if(!raw){const r=await env.ASSETS.fetch(new URL('/students-seed.json','https://student.local'));if(r.ok)raw=await r.text()}if(!raw)return null;try{const x=JSON.parse(raw);return (x.students||[]).find(s=>String(s.id)===String(id))||null}catch{return null}}
function migrateSecondBimester(data){let x;try{x=JSON.parse(data)}catch{return null}if(!x||!Array.isArray(x.students))return null;if(x.stateVersion>=3)return null;x.stateVersion=3;return JSON.stringify(x)}
async function api(request,env){const url=new URL(request.url);
if(url.pathname==='/api/login'&&request.method==='POST'){const b=await request.json().catch(()=>({})),u=String(b.user||'').trim().toLowerCase(),p=String(b.pass||'');await ensure(env);let row=await env.DB.prepare('SELECT user,name,role,pass_hash FROM users WHERE user=?').bind(u).first();if(!row&&/^\d+$/.test(u)&&await hash(p)===STUDENT_PASS_HASH){const s=await studentFromState(env,u);if(s){await env.DB.prepare('INSERT OR IGNORE INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(String(s.id),s.name,'student',STUDENT_PASS_HASH).run();row=await env.DB.prepare('SELECT user,name,role,pass_hash FROM users WHERE user=?').bind(u).first()}}if(!row||row.pass_hash!==await hash(p))return Response.json({error:'Usuário ou senha inválidos.'},{status:401});const token=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');await env.DB.prepare('INSERT INTO sessions(token,user,expires_at) VALUES(?,?,?)').bind(token,u,Math.floor(Date.now()/1000)+2592000).run();return new Response(JSON.stringify({user:{user:u,name:row.name,role:row.role}}),{headers:{'Content-Type':'application/json','Set-Cookie':cookie('horizonte_session',token,2592000)}})}
if(url.pathname==='/api/logout'&&request.method==='POST'){const c=request.headers.get('Cookie')||'',m=c.match(/(?:^|;\s*)horizonte_session=([^;]+)/);if(m&&env.DB)await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(m[1]).run();return new Response('',{status:204,headers:{'Set-Cookie':cookie('horizonte_session','',0)}})}
if(url.pathname==='/api/me'){const u=await me(request,env);return u?Response.json({user:u}):Response.json({user:null},{status:401})}
if(url.pathname==='/api/student'){const u=await me(request,env);if(!u)return Response.json({error:'Não autenticado.'},{status:401});if(u.role!=='student')return Response.json({error:'Acesso exclusivo para alunos.'},{status:403});await ensure(env);const s=await studentFromState(env,u.user);if(!s)return Response.json({error:'Aluno não encontrado.'},{status:404});return Response.json({student:{id:String(s.id),name:s.name,unit:s.unit,class:s.class,grades:s.grades||{},attendance:s.attendance||{}}},{headers:{'Cache-Control':'no-store'}})}
if(url.pathname==='/api/state'){const u=await me(request,env);if(!u)return Response.json({error:'Não autenticado.'},{status:401});if(u.role==='student')return Response.json({error:'O acesso de aluno é somente leitura.'},{status:403});await ensure(env);if(request.method==='GET'){const r=await env.DB.prepare('SELECT data FROM app_state WHERE id=1').first();if(r){const migrated=migrateSecondBimester(r.data);if(migrated){await env.DB.prepare('UPDATE app_state SET data=?,updated_at=CURRENT_TIMESTAMP WHERE id=1').bind(migrated).run();return new Response(migrated,{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}return new Response(r.data,{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}return env.ASSETS.fetch(new URL('/demo-state.json',request.url))}const data=await request.text();try{const x=JSON.parse(data);if(!x||!Array.isArray(x.students))throw 0}catch{return Response.json({error:'Dados inválidos.'},{status:400})}await env.DB.prepare('INSERT INTO app_state(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=CURRENT_TIMESTAMP').bind(data).run();return Response.json({ok:true})}
if(url.pathname==='/api/users'){const u=await me(request,env);if(!u)return Response.json({error:'Não autenticado.'},{status:401});if(u.role!=='admin')return Response.json({error:'Acesso negado.'},{status:403});await ensure(env);if(request.method==='GET'){const rows=await env.DB.prepare("SELECT user,name,role FROM users WHERE role='professor' ORDER BY name").all();return Response.json({users:rows.results||[]})}if(request.method==='POST'){const b=await request.json().catch(()=>({})),name=String(b.name||'').trim(),user=String(b.user||'').trim().toLowerCase(),pass=String(b.pass||'');if(!name||!user||!pass)return Response.json({error:'Nome, usuário e senha são obrigatórios.'},{status:400});if(!/^[a-z0-9._-]+$/.test(user))return Response.json({error:'Usuário inválido.'},{status:400});if(pass.length<6)return Response.json({error:'A senha deve ter pelo menos 6 caracteres.'},{status:400});const exists=await env.DB.prepare('SELECT user FROM users WHERE user=?').bind(user).first();if(exists)return Response.json({error:'Este usuário já existe.'},{status:409});await env.DB.prepare('INSERT INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(user,name,'professor',await hash(pass)).run();return Response.json({ok:true,user:{user,name,role:'professor'}})}if(request.method==='DELETE'){const user=String(url.searchParams.get('user')||'').trim().toLowerCase();if(!user)return Response.json({error:'Usuário não informado.'},{status:400});await env.DB.prepare("DELETE FROM users WHERE user=? AND role='professor'").bind(user).run();return Response.json({ok:true})}}
return null}
const GRADE_FIX=`(function(){
(function(){
 let active=null;
 function avg(g){const v=['n1','n2','n3','n4'].map(k=>g&&g[k]).filter(v=>v!==''&&v!=null&&!Number.isNaN(Number(v))).map(Number);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
 function table(){return document.getElementById('gradeTable')}
 function redrawMedia(){
   const t=table(), p=Number(document.getElementById('gradePeriod')?.value||2), sub=document.getElementById('gradeSubject')?.value;
   if(!t||!window.db||!sub)return;
   t.querySelectorAll('tr').forEach(tr=>{const i=tr.querySelector('.gi');if(!i)return;const s=db.students.find(x=>String(x.id)===String(i.dataset.id));const g=s?.grades?.[p]?.[sub]||{};const m=avg(g);const cell=tr.querySelector('.grade-media');if(cell)cell.textContent=m==null?'—':m.toFixed(2);});
 }
 function guard(){
   const t=table();if(!t||t.dataset.mediaGuard)return;
   t.dataset.mediaGuard='1';
   t.addEventListener('focusin',e=>{const i=e.target.closest('.gi,.gradeInput');if(i)active=i},true);
   t.addEventListener('input',e=>{const i=e.target.closest('.gi,.gradeInput');if(!i)return;active=i;});
   t.addEventListener('change',e=>{const i=e.target.closest('.gi,.gradeInput');if(!i)return;const s=db.students.find(x=>String(x.id)===String(i.dataset.id)),p=Number(document.getElementById('gradePeriod')?.value||2),sub=document.getElementById('gradeSubject')?.value;if(!s||!sub)return;s.grades??={};s.grades[p]??={};s.grades[p][sub]??={};const g=s.grades[p][sub],raw=String(i.value).trim().replace(',','.');g[i.dataset.k]=raw===''?'':Number(raw);g.media=avg(g);redrawMedia();});
   new MutationObserver(()=>{if(active&&document.activeElement!==active){const i=table().querySelector('.gi[data-id="'+CSS.escape(active.dataset.id)+'"][data-k="'+CSS.escape(active.dataset.k)+'"]');if(i){i.value=active.value;i.focus();try{i.setSelectionRange(i.value.length,i.value.length)}catch(e){}}redrawMedia()}}).observe(t,{childList:true,subtree:true});
 }
 function install(){
   const t=table();if(!t)return setTimeout(install,300);
   guard();
   if(!window.__originalSaveGrades&&typeof window.saveGrades==='function')window.__originalSaveGrades=window.saveGrades;
   window.saveGrades=async function(){
     const b=prompt('Digite o código do crachá do professor para salvar/fechar as notas:');
     if(b!=='PROF2026'){alert('Crachá inválido.');return}
     const p=Number(document.getElementById('gradePeriod')?.value||2),sub=document.getElementById('gradeSubject')?.value;
     document.querySelectorAll('#gradeTable .gi').forEach(i=>{const s=db.students.find(x=>String(x.id)===String(i.dataset.id));if(!s||i.disabled)return;s.grades??={};s.grades[p]??={};s.grades[p][sub]??={};const g=s.grades[p][sub],raw=String(i.value).trim().replace(',','.');g[i.dataset.k]=raw===''?'':Number(raw);g.media=avg(g);});
     if(typeof window.save==='function')await window.save();
     redrawMedia();
     window.toast?.('Notas e médias salvas com sucesso.');
   };
 }
 install();
})();})()`
export default {async fetch(request,env){const path=new URL(request.url).pathname;if(path.startsWith('/api/')){try{const r=await api(request,env);if(r)return r}catch(e){return Response.json({error:e.message||'Erro interno.'},{status:500})}}const res=await env.ASSETS.fetch(request);const ct=res.headers.get('content-type')||'';if(request.method==='GET'&&ct.includes('text/html'))return new HTMLRewriter().on('body',{element(e){e.append('<script src="/bootstrap.js?v=20260908s"></script><script>'+GRADE_FIX.replace(/<\/script>/g,'<\\/script>')+'</script>',{html:true})}}).transform(res);return res}};