const ADMIN={user:'joaopedroadmin',name:'João Pedro',role:'admin',hash:'9b6b5cf336a76742393239b8d6d94f3b8e82c602ff4303bfb7e6382ae55108f3'};
const TEACHER={user:'leticiaramos',name:'Léticia Ramos',role:'professor',hash:'7f0773073aa4ec31c7673d17380d72b9c71fbf3a2be41b7a2467156896823bfe'};
async function hash(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function cookie(n,v,age){return `${n}=${v}; Max-Age=${age}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function sessionCookie(user,role,name){return btoa(JSON.stringify({user,role,name,exp:Date.now()+2592000000}))}
async function me(request,env){const c=request.headers.get('Cookie')||'';const m=c.match(/(?:^|;\s*)horizonte_session=([^;]+)/);if(m&&env.DB){const r=await env.DB.prepare('SELECT s.user,u.name,u.role FROM sessions s JOIN users u ON u.user=s.user WHERE s.token=? AND s.expires_at>?').bind(m[1],Math.floor(Date.now()/1000)).first();if(r)return r}const f=c.match(/(?:^|;\s*)horizonte_fallback=([^;]+)/);if(f)try{const x=JSON.parse(atob(decodeURIComponent(f[1])));if(x.exp>Date.now())return x}catch{}return null}
async function ensure(env){if(!env.DB)return;await env.DB.batch([env.DB.prepare('CREATE TABLE IF NOT EXISTS users (user TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,pass_hash TEXT NOT NULL)'),env.DB.prepare('CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY,user TEXT NOT NULL,expires_at INTEGER NOT NULL)'),env.DB.prepare('CREATE TABLE IF NOT EXISTS app_state (id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)')]);await env.DB.prepare('INSERT OR IGNORE INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(ADMIN.user,ADMIN.name,ADMIN.role,ADMIN.hash).run();await env.DB.prepare('INSERT OR IGNORE INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(TEACHER.user,TEACHER.name,TEACHER.role,TEACHER.hash).run()}
async function api(request,env){const url=new URL(request.url);if(url.pathname==='/api/login'&&request.method==='POST'){const b=await request.json().catch(()=>({}));const u=String(b.user||'').trim().toLowerCase(),p=String(b.pass||'');await ensure(env);let row=await env.DB?.prepare('SELECT user,name,role,pass_hash FROM users WHERE user=?').bind(u).first();if(!row){const f=u===ADMIN.user?ADMIN:u===TEACHER.user?TEACHER:null;if(f&&p){row={user:f.user,name:f.name,role:f.role,pass_hash:f.hash}}}if(!row||row.pass_hash!==await hash(p))return Response.json({error:'Usuário ou senha inválidos.'},{status:401});if(env.DB){const token=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');await env.DB.prepare('INSERT INTO sessions(token,user,expires_at) VALUES(?,?,?)').bind(token,u,Math.floor(Date.now()/1000)+2592000).run();return new Response(JSON.stringify({user:{user:u,name:row.name,role:row.role}}),{headers:{'Content-Type':'application/json','Set-Cookie':cookie('horizonte_session',token,2592000)}})}const token=sessionCookie(u,row.role,row.name);return new Response(JSON.stringify({user:{user:u,name:row.name,role:row.role}}),{headers:{'Content-Type':'application/json','Set-Cookie':cookie('horizonte_fallback',encodeURIComponent(token),2592000)}})}
if(url.pathname==='/api/logout'&&request.method==='POST'){const c=request.headers.get('Cookie')||'',m=c.match(/(?:^|;\s*)horizonte_session=([^;]+)/);if(m&&env.DB)await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(m[1]).run();return new Response('',{status:204,headers:{'Set-Cookie':cookie('horizonte_session','',0)}})}
if(url.pathname==='/api/me'){const u=await me(request,env);return u?Response.json({user:u}):Response.json({user:null},{status:401})}
if(url.pathname==='/api/state'){const u=await me(request,env);if(!u)return Response.json({error:'Não autenticado.'},{status:401});await ensure(env);if(request.method==='GET'){if(env.DB){const r=await env.DB.prepare('SELECT data FROM app_state WHERE id=1').first();if(r)return new Response(r.data,{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}const r=await env.ASSETS.fetch(new URL('/demo-state.json',request.url));return r}const data=await request.text();try{const x=JSON.parse(data);if(!x||!Array.isArray(x.students))throw 0}catch{return Response.json({error:'Dados inválidos.'},{status:400})}if(env.DB){await env.DB.prepare('INSERT INTO app_state(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=CURRENT_TIMESTAMP').bind(data).run()}return Response.json({ok:true})}
if(url.pathname==='/api/users'&&request.method==='POST'){const u=await me(request,env);if(!u)return Response.json({error:'Não autenticado.'},{status:401});if(u.role!=='admin')return Response.json({error:'Acesso negado.'},{status:403});const b=await request.json();await ensure(env);await env.DB.prepare('INSERT INTO users(user,name,role,pass_hash) VALUES(?,?,?,?)').bind(String(b.user).trim().toLowerCase(),String(b.name).trim(),'professor',await hash(String(b.pass))).run();return Response.json({ok:true})}
if(url.pathname==='/api/users'&&request.method==='DELETE'){const u=await me(request,env);if(!u||u.role!=='admin')return Response.json({error:'Acesso negado.'},{status:403});await env.DB.prepare('DELETE FROM users WHERE user=? AND role=\'professor\'').bind(url.searchParams.get('user')).run();return Response.json({ok:true})}return null}
export default {async fetch(request,env){if(new URL(request.url).pathname.startsWith('/api/')){const r=await api(request,env);if(r)return r}return env.ASSETS.fetch(request)}};